project:
  type: website
  output-dir: docs

website:
  title: "Around the Island of Mo'orea"
  description: "Environmental DNA and ecological mapping to guide coral reef restoration around Mo'orea, French Polynesia."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:dashboard
      - href: Time_series.qmd
        text: Time series
      - href: https://moorea-surveys.community.guardianconnector.net/
        text: Acoustic Dashboard
        target: "_blank"
      - href: Data_repository.qmd
        text: Repository
      - href: Publications.qmd
        text: Publications
      - href: Team.qmd
        text: Team
    
  sidebar:
    - id: dashboard
      title: "Data Dashboard"
      style: "docked"
      background: light
      collapse-level: 2
      width: 200  # Add this to make sidebar narrower
      contents:
          - dashboard/Habitat_type.qmd
          - dashboard/Distance_from_shore.qmd
          - dashboard/Turbinaria.qmd
          - dashboard/Water_quality_index.qmd
          - dashboard/Benthic_coral_cover.qmd
          - dashboard/Bleaching.qmd
          - dashboard/Coral_mortality.qmd
          - dashboard/Temperature.qmd
          - dashboard/Bacterial_eDNA.qmd
          - dashboard/Fish_eDNA.qmd
          - dashboard/Acoustic_data.qmd
          - dashboard/Fish_visual_surveys.qmd
          
          
      

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true
    include-in-header: meta-description.html

editor: visual
