project:
  type: website
  output-dir: docs

website:
  title: "Around The Island of Moorea"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:dashboard
      - href: Time_series.qmd
        text: Time series
      - href: Data_repository.qmd
        text: Repository
      - href: Team.qmd
        text: Team
    
  sidebar:
    - id: dashboard
      title: "Data Dashboard"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
          - dashboard/Habitat_type.qmd
          - dashboard/Distance_from_shore.qmd
          - dashboard/Turbinaria.qmd
          - dashboard/Water_quality_index.qmd
          - dashboard/Benthic_coral_cover.qmd
          - dashboard/Benthic_algal_cover.qmd
          - dashboard/Bleaching.qmd
          - dashboard/Bacterial_eDNA.qmd
          - dashboard/Fish_eDNA.qmd
          - dashboard/Fish_visual_surveys.qmd
          
          
      

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

editor: visual
