project:
  type: website
  output-dir: docs

website:
  title: "Around The Island of Moorea"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:dashboard
      - href: Data_overview.qmd
        text: Data Dashboard
      - href: Time_series.qmd
        text: Time series
      - href: Data_repository.qmd
        text: Repository
      - href: Team.qmd
        text: Team
    
  sidebar:
    - id: dashboard
      title: "Data Dashboard 2"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
          - dashboard/Habitat_type.qmd
          - dashboard/Distance_from_shore.qmd
      

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

editor: visual
